#!/bin/bash

echo "🚀 AI Assistant Quick Start with Google Gemini (FREE)"
echo ""
echo "1️⃣ GET YOUR FREE API KEY:"
echo "   Visit: https://aistudio.google.com/app/apikey"
echo "   - Sign in with Google"
echo "   - Click 'Create API Key'"
echo "   - Copy your key"
echo ""
echo "2️⃣ ADD KEY TO .env.local:"
echo "   Open: .env.local"
echo "   Replace: YOUR_GEMINI_API_KEY_HERE"
echo "   With: Your actual API key"
echo ""
echo "3️⃣ START THE APP:"
echo "   npm start"
echo ""
echo "4️⃣ TEST THE AI:"
echo "   - Open: http://localhost:3000"
echo "   - Click chat button (bottom-right)"
echo "   - Try: 'Hello, find me a villa'"
echo ""
echo "✅ 100% FREE - No credit card required"
echo "✅ 60 requests/minute on free tier"
echo "✅ Powerful Gemini 1.5 Flash model"
echo ""
echo "Need help? Check GEMINI_SETUP.md"
