import {
  HomeIcon,
  CalendarIcon,
  EnvelopeIcon,
  HeartIcon,
  BanknotesIcon,
  ChatBubbleLeftIcon,
  EyeIcon,
  DocumentTextIcon,
  FolderOpenIcon,
  ChartBarIcon,
  MapPinIcon,
  MagnifyingGlassIcon,
  ClockIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  KeyIcon,
  CurrencyEuroIcon,
} from '@heroicons/react/24/outline';
import { Property, Appointment, Message, Demand, BuyerDocument, StatItem, SellerDocument, SellerStat, StatsPerProperty, Lease, LessorRentalProperty } from './types';

export const buyerSavedProperties: Property[] = [
  {
    id: 1,
    title: 'Ma Villa Méditerranéenne',
    location: 'Nice, Côte d\'Azur',
    price: '2 500 000 €',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '420 m²',
    bedrooms: 6,
    bathrooms: 5,
    type: 'buy',
    description: 'Superbe villa méditerranéenne située à Nice, offrant une vue panoramique sur la mer. Cette propriété d\'exception dispose de 6 chambres, 5 salles de bain, un jardin paysager et une piscine à débordement.',
    features: ['Piscine', 'Jardin', 'Terrasse', 'Garage', 'Air conditionné', 'Ascenseur', 'Cheminée', 'Double vitrage', 'Fibre optique', 'Vidéosurveillance'],
    yearBuilt: 2018,
    landSize: '3 500 m²',
    score: 92,
    isNew: true,
    demandLabel: 'Villa - Nice',
  },
  {
    id: 2,
    title: 'Appartement Centre Ville',
    location: 'Lyon, Presqu\'île',
    price: '15 000 €/mois',
    image: 'https://images.pexels.com/photos/7031407/pexels-photo-7031407.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '120 m²',
    bedrooms: 3,
    bathrooms: 2,
    type: 'rent',
    score: 85,
    isNew: true,
    demandLabel: 'Investissement - Lyon',
  },
  {
    id: 3,
    title: 'Chalet de Luxe',
    location: 'Courchevel, Alpes',
    price: '4 800 000 €',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '350 m²',
    bedrooms: 5,
    bathrooms: 4,
    type: 'buy',
    score: 78,
    isNew: false,
    demandLabel: 'Villa - Nice',
  },
  {
    id: 4,
    title: 'Penthouse Vue Mer',
    location: 'Cannes, Croisette',
    price: '3 200 000 €',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '280 m²',
    bedrooms: 4,
    bathrooms: 3,
    type: 'buy',
    score: 71,
    isNew: false,
    demandLabel: 'Villa - Nice',
  },
];

export const buyerDashboardStats: StatItem[] = [
  { label: 'Demandes actives', value: '2', icon: MagnifyingGlassIcon, color: 'emerald' },
  { label: 'Biens proposés', value: '12', icon: HomeIcon, color: 'blue' },
  { label: 'Propositions consultées', value: '5', icon: EyeIcon, color: 'amber' },
  { label: 'Rendez-vous à venir', value: '3', icon: CalendarIcon, color: 'purple' },
  { label: 'Messages non lus', value: '3', icon: EnvelopeIcon, color: 'rose' },
  { label: 'Documents manquants', value: '1', icon: ExclamationTriangleIcon, color: 'red' },
];

export const ownerProperties: Property[] = [
  {
    id: 1,
    title: 'Ma Villa Méditerranéenne',
    location: 'Nice, Côte d\'Azur',
    price: '2 500 000 €',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '420 m²',
    bedrooms: 6,
    bathrooms: 5,
    status: 'En vente',
    reference: 'RES-2026-001',
    mandate: 'Exclusif - 01/06/2026',
    views: 245,
    favorites: 18,
    inquiries: 7,
    visitsThisMonth: 5,
  },
  {
    id: 2,
    title: 'Appartement Centre Ville',
    location: 'Lyon, Presqu\'île',
    price: '15 000 €/mois',
    image: 'https://images.pexels.com/photos/7031407/pexels-photo-7031407.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '120 m²',
    bedrooms: 3,
    bathrooms: 2,
    status: 'En location',
    reference: 'LOC-2026-001',
    mandate: 'Gestion - 15/05/2026',
    views: 132,
    favorites: 9,
    inquiries: 4,
    visitsThisMonth: 3,
  },
];

export const ownerStats: StatItem[] = [
  { label: 'Propriétés actives', value: '2', icon: HomeIcon },
  { label: 'Visites ce mois', value: '8', icon: CalendarIcon },
  { label: 'Demandes reçues', value: '11', icon: EnvelopeIcon },
  { label: 'Revenus mensuels', value: '2 200 €', icon: BanknotesIcon },
];

export const sellerDashboardStats: SellerStat[] = [
  { label: 'Propriétés actives', value: '2', icon: HomeIcon },
  { label: 'Visites ce mois', value: '8', icon: EyeIcon, trend: '+15%', trendUp: true },
  { label: 'Demandes reçues', value: '11', icon: EnvelopeIcon, trend: '+12%', trendUp: true },
  { label: 'Revenus mensuels', value: '2 200 €', icon: BanknotesIcon, trend: '+12%', trendUp: true },
  { label: 'Mandat actif', value: 'J-30', icon: ShieldCheckIcon },
  { label: 'Messages non lus', value: '2', icon: ChatBubbleLeftIcon },
];

export const sellerDocuments: SellerDocument[] = [
  { id: 1, name: 'DPE - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 2, name: 'Amiante - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 3, name: 'Bail - Appartement Centre Ville', category: 'Contrat', property: 'Appartement Centre Ville', date: '01/05/2026' },
  { id: 4, name: 'Titre de propriété - Villa', category: 'Titre de propriété', property: 'Ma Villa Méditerranéenne', date: '01/06/2026' },
  { id: 5, name: 'Diagnostic électrique - Villa', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '10/03/2026' },
  { id: 6, name: 'Contrat de location - Appartement', category: 'Contrat', property: 'Appartement Centre Ville', date: '01/05/2026' },
];

export const statsPerProperty: StatsPerProperty[] = [
  { name: 'Ma Villa Méditerranéenne', visits: 32, demands: 10, conversion: '31%', revenue: '-' },
  { name: 'Appartement Centre Ville', visits: 13, demands: 8, conversion: '61%', revenue: '2 200 €' },
];

export const appointmentsData: Appointment[] = [
  {
    id: 1,
    title: 'Visite - Villa moderne à Cannes',
    date: '15/12/2025',
    time: '14:00',
    location: '15 Bd de la Croisette, Cannes',
    status: 'Confirmé',
    advisor: 'Sophie Martin',
    type: 'Visite',
    propertyName: 'Villa moderne à Cannes',
  },
  {
    id: 2,
    title: 'RDV Estimation',
    date: '18/12/2025',
    time: '10:00',
    location: 'Agence Square Meter - Nice',
    status: 'En attente',
    advisor: 'Marc Dubois',
    type: 'Estimation',
    propertyName: 'Ma Villa Méditerranéenne',
  },
  {
    id: 3,
    title: 'Visite - Appartement',
    date: '22/12/2025',
    time: '16:00',
    location: '12 Rue de la Paix, Lyon',
    status: 'Confirmé',
    advisor: 'Sophie Martin',
    type: 'Visite',
    propertyName: 'Appartement Centre Ville',
  },
];

export const messages: Message[] = [
  {
    id: 1,
    sender: 'Sophie Martin',
    role: 'Conseillère',
    content: 'Bonjour ! Je voulais confirmer notre visite prévue ce samedi à 14h.',
    time: '2h',
    unread: true,
  },
  {
    id: 2,
    sender: 'Marc Dubois',
    role: 'Expert en évaluation immobilière',
    content: "J'ai bien reçu votre demande d'estimation pour votre villa à Nice.",
    time: '1j',
    unread: false,
  },
  {
    id: 3,
    sender: 'Sophie Martin',
    role: 'Conseillère immobilière',
    content: 'En attente de réponse concernant la proposition que je vous ai envoyée.',
    time: '3j',
    unread: false,
  },
  {
    id: 4,
    sender: 'Agence Square Meter',
    role: 'Service client',
    content: 'Votre dossier de financement a été mis à jour.',
    time: '5j',
    unread: true,
  },
];

export const buyerDemands: Demand[] = [
  {
    id: 1,
    title: 'Villa - Nice / Côte d\'Azur',
    criteria: '2 000 000 - 3 000 000 € · 5 ch. · 300+ m²',
    location: 'Nice, Côte d\'Azur',
    status: 'Active',
    propositions: 5,
    priceRange: '2 000 000 - 3 000 000 €',
    details: '5 ch. · 300+ m² · Jardin',
  },
  {
    id: 2,
    title: 'Investissement - Lyon',
    criteria: '500 000 - 800 000 € · 3 ch. · 100+ m²',
    location: 'Lyon, Presqu\'île',
    status: 'Active',
    propositions: 3,
    priceRange: '500 000 - 800 000 €',
    details: '3 ch. · 100+ m² · Centre',
  },
  {
    id: 3,
    title: 'Résidence secondaire - Biarritz',
    criteria: '1 500 000 - 2 000 000 € · 4 ch. · 200+ m²',
    location: 'Biarritz',
    status: 'Terminée',
    propositions: 0,
    priceRange: '1 500 000 - 2 000 000 €',
    details: '4 ch. · 200+ m² · Vue mer',
  },
];

export const buyerDocuments: BuyerDocument[] = [
  { id: 1, name: "Pièce d'identité", status: 'Vérifié', date: '10/01/2024', statusType: 'verified' },
  { id: 2, name: 'Justificatif de domicile', status: 'En attente', date: '08/01/2024', statusType: 'pending' },
  { id: 3, name: 'Compromis de vente', status: 'Signé', date: '05/01/2024', statusType: 'signed' },
  { id: 4, name: 'Attestation de prêt', status: 'Manquant', date: '-', statusType: 'missing' },
];

export const ownerDocuments = [
  { id: 1, name: 'DPE - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 2, name: 'Amiante - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 3, name: 'Bail - Appartement Centre Ville', category: 'Contrat', property: 'Appartement Centre Ville', date: '01/05/2026' },
  { id: 4, name: 'Titre de propriété - Villa', category: 'Titre de propriété', property: 'Ma Villa Méditerranéenne', date: '01/06/2026' },
];

export const tenantDashboardStats: StatItem[] = [
  { label: 'Demandes actives', value: '2', icon: MagnifyingGlassIcon, color: 'emerald' },
  { label: 'Biens proposés', value: '12', icon: HomeIcon, color: 'blue' },
  { label: 'Propositions consultées', value: '5', icon: EyeIcon, color: 'amber' },
  { label: 'Rendez-vous à venir', value: '3', icon: CalendarIcon, color: 'purple' },
  { label: 'Messages non lus', value: '3', icon: EnvelopeIcon, color: 'rose' },
  { label: 'Documents manquants', value: '1', icon: ExclamationTriangleIcon, color: 'red' },
];

export const tenantProperties: Property[] = [
  {
    id: 1,
    title: 'Appartement T3 - Centre Ville',
    location: 'Lyon, Presqu\'île',
    price: '1 200 €/mois',
    image: 'https://images.pexels.com/photos/7031407/pexels-photo-7031407.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '75 m²',
    bedrooms: 2,
    bathrooms: 1,
    type: 'rent',
    description: 'Très bel appartement T3 de 75 m² situé en plein cœur de Lyon, dans le quartier de la Presqu\'île. Proche de toutes commodités (métro, commerces, écoles).',
    features: ['Ascenseur', 'Balcon', 'Cave', 'Fibre optique', 'Air conditionné', 'Double vitrage', 'Videophone'],
    yearBuilt: 2018,
    score: 95,
    isNew: true,
    demandLabel: 'Appartement - Lyon Centre',
  },
  {
    id: 2,
    title: 'Maison 4 pièces - Périphérie',
    location: 'Villeurbanne',
    price: '1 500 €/mois',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '100 m²',
    bedrooms: 3,
    bathrooms: 2,
    type: 'rent',
    score: 82,
    isNew: true,
    demandLabel: 'Maison - Villeurbanne',
  },
  {
    id: 3,
    title: 'Studio Meublé - Bellecour',
    location: 'Lyon, Bellecour',
    price: '650 €/mois',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '25 m²',
    bedrooms: 1,
    bathrooms: 1,
    type: 'rent',
    score: 78,
    isNew: false,
    demandLabel: 'Studio - Étudiant',
  },
  {
    id: 4,
    title: 'Appartement T4 - Brotteaux',
    location: 'Lyon, Brotteaux',
    price: '1 800 €/mois',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '90 m²',
    bedrooms: 3,
    bathrooms: 1,
    type: 'rent',
    score: 71,
    isNew: false,
    demandLabel: 'Appartement - Lyon Centre',
  },
];

export const tenantDemands: Demand[] = [
  {
    id: 1,
    title: 'Appartement - Lyon Centre',
    criteria: '800 - 1 200 €/mois · 3 ch. · 70+ m²',
    location: 'Lyon, Presqu\'île',
    status: 'Active',
    propositions: 5,
    priceRange: '800 - 1 200 €/mois',
    details: '3 ch. · 70+ m² · Ascenseur',
  },
  {
    id: 2,
    title: 'Maison - Villeurbanne',
    criteria: '1 200 - 1 800 €/mois · 4 ch. · 90+ m²',
    location: 'Villeurbanne',
    status: 'Active',
    propositions: 3,
    priceRange: '1 200 - 1 800 €/mois',
    details: '4 ch. · 90+ m² · Jardin',
  },
  {
    id: 3,
    title: 'Studio - Étudiant',
    criteria: '400 - 600 €/mois · 1 ch. · 20+ m²',
    location: 'Lyon, Centre',
    status: 'Terminée',
    propositions: 0,
    priceRange: '400 - 600 €/mois',
    details: '1 ch. · 20+ m² · Meublé',
  },
];

export const tenantDocuments: BuyerDocument[] = [
  { id: 1, name: "Pièce d'identité", status: 'Vérifié', date: '10/01/2024', statusType: 'verified' },
  { id: 2, name: 'Justificatif de domicile', status: 'En attente', date: '08/01/2024', statusType: 'pending' },
  { id: 3, name: 'Fiches de paie (3 derniers)', status: 'Manquant', date: '-', statusType: 'missing' },
  { id: 4, name: 'Dossier de location', status: 'Signé', date: '01/06/2024', statusType: 'signed' },
  { id: 5, name: 'Bail signé', status: 'Manquant', date: '-', statusType: 'missing' },
];

export const lessorDashboardStats: StatItem[] = [
  { label: 'Propriétés en location', value: '2', icon: HomeIcon, color: 'emerald' },
  { label: "Taux d'occupation", value: '85%', icon: ChartBarIcon, color: 'blue' },
  { label: 'Demandes reçues', value: '11', icon: EnvelopeIcon, color: 'amber' },
  { label: 'Revenus mensuels', value: '2 200 €', icon: BanknotesIcon, color: 'purple' },
  { label: 'Loyers impayés', value: '0', icon: ExclamationTriangleIcon, color: 'red' },
  { label: 'Baux à renouveler', value: '1', icon: DocumentTextIcon, color: 'orange' },
  { label: 'Messages non lus', value: '2', icon: ChatBubbleLeftIcon, color: 'rose' },
];

export const lessorRentalProperties: LessorRentalProperty[] = [
  {
    id: 1,
    title: 'Ma Villa Méditerranéenne',
    location: 'Nice, Côte d\'Azur',
    price: '1 500 €/mois',
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '420 m²',
    bedrooms: 6,
    bathrooms: 5,
    status: 'En location',
    reference: 'LOC-2026-001',
    mandate: 'Gestion - Mandat actif',
    views: 245,
    favorites: 18,
    inquiries: 3,
    visitsThisMonth: 5,
    tenant: 'M. Lambert',
    tenantEmail: 'lambert@email.com',
    tenantPhone: '+33 6 12 34 56 78',
    leaseStart: '01/06/2026',
    leaseEnd: '01/06/2028',
    rentAmount: '1 500 €/mois',
    depositAmount: '1 500 €',
    occupancyRate: 85,
    mandateEnd: '01/12/2026',
    mandateDaysLeft: 45,
  },
  {
    id: 2,
    title: 'Appartement Centre Ville',
    location: 'Lyon, Presqu\'île',
    price: '700 €/mois',
    image: 'https://images.pexels.com/photos/7031407/pexels-photo-7031407.jpeg?auto=compress&cs=tinysrgb&w=600',
    surface: '75 m²',
    bedrooms: 3,
    bathrooms: 2,
    status: 'En location',
    reference: 'LOC-2026-002',
    mandate: 'Gestion - Mandat actif',
    views: 132,
    favorites: 9,
    inquiries: 8,
    visitsThisMonth: 3,
    tenant: 'Mme Dupont',
    tenantEmail: 'dupont@email.com',
    tenantPhone: '+33 6 98 76 54 32',
    leaseStart: '01/06/2025',
    leaseEnd: '01/01/2026',
    rentAmount: '700 €/mois',
    depositAmount: '700 €',
    occupancyRate: 95,
    mandateEnd: '01/02/2026',
    mandateDaysLeft: 60,
  },
];

export const lessorStatsPerProperty: StatsPerProperty[] = [
  { name: 'Ma Villa Méditerranéenne', visits: 8, demands: 3, conversion: '37%', revenue: '1 500 €' },
  { name: 'Appartement Centre Ville', visits: 5, demands: 8, conversion: '62%', revenue: '700 €' },
];

export const lessorLeases: Lease[] = [
  {
    id: 1,
    property: 'Ma Villa Méditerranéenne',
    tenant: 'M. Lambert',
    startDate: '01/06/2026',
    endDate: '01/06/2028',
    rent: '1 500 €/mois',
    deposit: '1 500 €',
    status: 'Actif',
  },
  {
    id: 2,
    property: 'Appartement Centre Ville',
    tenant: 'Mme Dupont',
    startDate: '01/06/2025',
    endDate: '01/01/2026',
    rent: '700 €/mois',
    deposit: '700 €',
    status: 'À renouveler',
    renewableDays: 30,
  },
];

export const lessorDocuments: SellerDocument[] = [
  { id: 1, name: 'DPE - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 2, name: 'Amiante - Villa Méditerranéenne', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '15/01/2026' },
  { id: 3, name: 'Bail - Villa Méditerranéenne', category: 'Bail', property: 'Ma Villa Méditerranéenne', date: '01/06/2026' },
  { id: 4, name: 'Bail - Appartement Centre Ville', category: 'Bail', property: 'Appartement Centre Ville', date: '01/06/2025' },
  { id: 5, name: 'Titre de propriété - Villa', category: 'Titre de propriété', property: 'Ma Villa Méditerranéenne', date: '01/06/2026' },
  { id: 6, name: 'Titre de propriété - Appartement', category: 'Titre de propriété', property: 'Appartement Centre Ville', date: '15/05/2026' },
  { id: 7, name: 'Diagnostic électrique - Villa', category: 'Diagnostic', property: 'Ma Villa Méditerranéenne', date: '10/03/2026' },
  { id: 8, name: 'Contrat de gestion locative', category: 'Contrat', property: 'Ma Villa Méditerranéenne', date: '01/06/2026' },
];

export const receivedDemands = [
  {
    id: 1,
    demandeur: 'Jean Dupont',
    property: 'Ma Villa Méditerranéenne',
    type: 'Demande de visite',
    date: '15/06/2026',
    status: 'En attente',
    message: 'Bonjour, je suis intéressé par la villa. Pouvez-vous me proposer une visite ?',
  },
  {
    id: 2,
    demandeur: 'Sophie Martin',
    property: 'Appartement Centre Ville',
    type: 'Question',
    date: '14/06/2026',
    status: 'En attente',
    message: 'Les charges sont-elles comprises dans le loyer ?',
  },
  {
    id: 3,
    demandeur: 'Marc Dubois',
    property: 'Ma Villa Méditerranéenne',
    type: 'Demande d\'estimation',
    date: '12/06/2026',
    status: 'Traité',
    message: 'Je souhaite faire estimer ma propriété avant mise en vente.',
  },
];
